# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeeplinkNavigator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeeplinkNavigator
   pod 'ReactiveCocoa', '2.5'
   def testing_pods
#   pod 'Quick'
#   pod 'Nimble'
   end


  target 'DeeplinkNavigatorTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end

end

target 'example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example

end
